### ISSUE TITLE
Received panic when parsing a ruby anchoring example

### ISSUE THREAD

**Issue by danielhoherd** [solarkennedy/uq#1]
Problematic data, found here: https://gist.github.com/bowsersenior/979804

```
default: &DEFAULT
  URL: stooges.com
  stooges: &stooge_list
    larry: first_stooge
    moe: second_stooge
    curly: third_stooge

development:
  <<: *DEFAULT
  URL: stooges.local
  stooges:
    shemp: fourth_stooge

test:
  <<: *DEFAULT
  URL: test.stooges.qa
  stooges:
    <<: *stooge_list
    shemp: fourth_stooge
```

Output from `uq filename.yaml`:

```
panic: runtime error: hash of unhashable type map[interface {}]interface {} [recovered]
    panic: runtime error: hash of unhashable type map[interface {}]interface {}

goroutine 1 [running]:
github.com/cloudfoundry-incubator/candiedyaml.recovery(0xc20808bc38)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/cloudfoundry-incubator/candiedyaml/decode.go:83 +0x9c
github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).mappingInterface(0xc208020700, 0xc20803a300)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/cloudfoundry-incubator/candiedyaml/decode.go:614 +0xff
github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).valueInterface(0xc208020700, 0x0, 0x0)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/cloudfoundry-incubator/candiedyaml/decode.go:547 +0xa15
github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).mappingInterface(0xc208020700, 0xc2080336d0)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/cloudfoundry-incubator/candiedyaml/decode.go:614 +0xbd
github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).mapping(0xc208020700, 0x5ad000, 0xc2080336d0, 0xd4)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/cloudfoundry-incubator/candiedyaml/decode.go:395 +0x242
github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).parse(0xc208020700, 0x5a0040, 0xc2080336d0, 0x16)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/cloudfoundry-incubator/candiedyaml/decode.go:206 +0x96e
github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).alias(0xc208020700, 0x5a0040, 0xc2080336d0, 0x16)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/cloudfoundry-incubator/candiedyaml/decode.go:534 +0x2d9
github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).valueInterface(0xc208020700, 0x0, 0x0)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/cloudfoundry-incubator/candiedyaml/decode.go:553 +0x2b7
github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).mappingInterface(0xc208020700, 0x0)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/cloudfoundry-incubator/candiedyaml/decode.go:614 +0xbd
github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).valueInterface(0xc208020700, 0x0, 0x0)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/cloudfoundry-incubator/candiedyaml/decode.go:547 +0xa15
github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).mappingInterface(0xc208020700, 0xc208033380)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/cloudfoundry-incubator/candiedyaml/decode.go:614 +0xbd
github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).mapping(0xc208020700, 0x5ad000, 0xc208033380, 0xd4)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/cloudfoundry-incubator/candiedyaml/decode.go:395 +0x242
github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).parse(0xc208020700, 0x5a0040, 0xc208033380, 0x16)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/cloudfoundry-incubator/candiedyaml/decode.go:206 +0x96e
github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).document(0xc208020700, 0x5a0040, 0xc208033380, 0x16)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/cloudfoundry-incubator/candiedyaml/decode.go:182 +0x185
github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).Decode(0xc208020700, 0x5a0040, 0xc208033380, 0x0, 0x0)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/cloudfoundry-incubator/candiedyaml/decode.go:133 +0x28a
github.com/cloudfoundry-incubator/candiedyaml.Unmarshal(0xc208020380, 0x148, 0x348, 0x5a0040, 0xc208033380, 0x0, 0x0)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/cloudfoundry-incubator/candiedyaml/decode.go:102 +0x10a
github.com/ghodss/yaml.yamlToJSON(0xc208020380, 0x148, 0x348, 0xc20800bfa0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/ghodss/yaml/yaml.go:80 +0xb3
github.com/ghodss/yaml.Unmarshal(0xc208020380, 0x148, 0x348, 0x5a0040, 0xc208033370, 0x0, 0x0)
    /src/upstream/lucid/0.0.2/uq-0.0.2/src/github.com/ghodss/yaml/yaml.go:32 +0xf4
main.parseData(0xc208020380, 0x148, 0x348, 0x634510, 0x4, 0x0, 0x0, 0x0, 0x0)
    /src/upstream/lucid/0.0.2/uq-0.0.2/main.go:30 +0x1b9
main.main()
    /src/upstream/lucid/0.0.2/uq-0.0.2/main.go:114 +0x3bc

goroutine 2 [runnable]:
runtime.forcegchelper()
    /usr/lib/go/src/runtime/proc.go:90
runtime.goexit()
    /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
    /usr/lib/go/src/runtime/mgc0.go:82
runtime.goexit()
    /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
    /usr/lib/go/src/runtime/malloc.go:712
runtime.goexit()
    /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by danielhoherd** [comment]
This works fine when you remove the `stooge_list` anchors.

**Comment by solarkennedy** [comment]
I don't believe this is happening anymore with 0.0.3+.

I get 

```
{
  "default": {
    "URL": "stooges.com",
    "stooges": {
      "curly": "third_stooge",
      "larry": "first_stooge",
      "moe": "second_stooge"
    }
  },
  "development": {
    "URL": "stooges.local",
    "stooges": {
      "shemp": "fourth_stooge"
    }
  },
  "test": {
    "URL": "test.stooges.qa",
    "stooges": {
      "curly": "third_stooge",
      "larry": "first_stooge",
      "moe": "second_stooge",
      "shemp": "fourth_stooge"
    }
  }
}
```
